spring:
  boot:
    admin:
      client:
        url: "http://localhost:4608"

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
